Finance2/Controllers/BancoController.cs
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Finance2.Controllers
{
    public class BancoController : Finance.Controllers.BancoController
    {

        public override Task<ActionResult> Indice()
        {
            return base.Indice();
        }
    }
}

Finance2/Controllers/DespesaController.cs
using Finance.Models;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Finance2.Controllers
{
    public class DespesaController : Finance.Controllers.DespesaController
    {
        //private FinanceContext context = new FinanceContext();

        public override async Task<ActionResult> Indice()
        {
            return View(await context.Despesas.ToListAsync());
        }

        public override Task<ActionResult> Criar()
        {
            return base.Criar();
        }

        [HttpPost]
        public override Task<ActionResult> Criar(Despesa despesa)
        {
            return base.Criar(despesa);
        }
    }
}

Finance2/Controllers/ReceitaController.cs
using Finance.Models;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Finance2.Controllers
{
    public class ReceitaController : Finance.Controllers.ReceitaController
    {
        //private FinanceContext context = new FinanceContext();

        public override async Task<ActionResult> Indice()
        {
            return View(await context.Receitas.ToListAsync());
        }

        public override Task<ActionResult> Criar()
        {
            return base.Criar();
        }

        [HttpPost]
        public override Task<ActionResult> Criar(Receita receita)
        {
            return base.Criar(receita);
        }
    }
}

Finance2/Views/Despesa/Criar.cshtml
@model Finance.Models.Despesa

@{
    /**/

    ViewBag.Title = "Criar";
}

<h3>Criar Despesa</h3>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    @Html.Partial("_CriarOuEditar", Model)

    <p>
        <input class="tiny success button" type="submit" value="Criar" />
    </p>
}

<div>
    @Html.ActionLink("Voltar para listagem", "Indice")
</div>

Finance2/Views/Despesa/Indice.cshtml
@model IEnumerable<Finance.Models.Despesa>

@{
    ViewBag.Title = "Indice";
}

<h2>Indice</h2>

<p>
    @Html.ActionLink("Criar Novo", "Criar", new { }, new { @class = "button tiny primary" })
</p>
<table>
    <thead>
        <tr>
            <th>
                Descricao
            </th>
            <th>
                Valor
            </th>
            @*<th>
                DespesaCategoria
            </th>
            <th></th>*@
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @item.Descricao
            </td>
            <td>
                @String.Format("{0:N2}", item.Valor)
            </td>
            @*<td>
                @Html.DisplayTextFor(_ => item.DespesaCategoria.Nome).ToString()
            </td>*@

            @*<td>
                @Html.ActionLink("Editar", "Editar", new { id = item.DespesaId }, new { @class = "button tiny primary" })
                @Html.ActionLink("Detalhes", "Detalhes", new { id = item.DespesaId }, new { @class = "button tiny secondary" })
                @Html.ActionLink("Excluir", "Excluir", new { id = item.DespesaId }, new { @class = "button tiny alert" })
            </td>*@
        </tr>
    }

</table>

Finance2/Views/Despesa/_CriarOuEditar.cshtml
@model Finance.Models.Despesa

@* This partial view defines form fields that will appear when creating and editing entities *@

<div class="editor-label">
    @Html.LabelFor(model => model.Descricao)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.Descricao)
    @Html.ValidationMessageFor(model => model.Descricao)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.Valor)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.Valor)
    @Html.ValidationMessageFor(model => model.Valor)
</div>

<div class="editor-label">
    DespesaCategoria
</div>
<div class="editor-field">
    @Html.DropDownListFor(model => model.DespesaCategoriaId, ((IEnumerable<Finance.Models.DespesaCategoria>)ViewBag.DespesaCategoria).Select(option => new SelectListItem {
        Text = Html.DisplayTextFor(_ => option.Nome).ToString(),
        Value = option.DespesaCategoriaId.ToString(),
        Selected = (Model != null) && (option.DespesaCategoriaId == Model.DespesaCategoriaId)
    }), "Selecione um item...")
    @Html.ValidationMessageFor(model => model.DespesaCategoriaId)
</div>

Finance2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Finance2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Finance2/Views/Home/Index.cshtml
<div class="row">
    <div class="large-12 columns">
        <h1>Welcome to Finance Two</h1>
    </div>
</div>

Finance2/Views/Shared/_Layout.cshtml
@*@using StackExchange.Profiling;
    @using StackExchange.Profiling.Mvc*@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Finance</title>
    @Styles.Render("~/Content/bootstrap/css")
    @Scripts.Render("~/bundles/bsmodernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Finance", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Contas", "Indice", "Conta")</li>
                    <li>@Html.ActionLink("Transferencias", "Indice", "Transferencia")</li>
                    <li>@Html.ActionLink("Bancos", "Indice", "Banco")</li>
                    <li>@Html.ActionLink("Despesas", "Indice", "Despesa")</li>
                    <li>@Html.ActionLink("Receitas", "Indice", "Receita")</li>
                    <li>@Html.ActionLink("Receitas Categorias", "Indice", "ReceitaCategoria")</li>
                    <li>@Html.ActionLink("Despesas Categorias", "Indice", "DespesaCategoria")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @*@MiniProfiler.Current.RenderIncludes(position: RenderPosition.Right, showTrivial: false, showTimeWithChildren: false, startHidden: false)*@

</body>
</html>

Finance2/Views/Shared/_LayoutFoundation.cshtml
@*@using StackExchange.Profiling;
    @using StackExchange.Profiling.Mvc*@
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8" />

    @*Set the viewport width to device width for mobile *@
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewBag.Title - Finance</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    @Styles.Render("~/Content/foundation/css")

    @RenderSection("head", required: false)

    <style>
        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #333333;
        }

        li {
            float: left;
        }

            li a {
                display: block;
                color: white;
                text-align: center;
                padding: 16px;
                text-decoration: none;
            }

                li a:hover {
                    background-color: #111111;
                }
    </style>
</head>
<body>

    @*<ul class="menu">
            <li class="is-active"><a>Home</a></li>
            <li><a>About</a></li>
            <li><a>Nachos</a></li>
        </ul>*@

    <div class="row">

        <ul>
            <li>@Html.ActionLink("Bancos", "Indice", "Banco")</li>
            <li>@Html.ActionLink("Despesas", "Indice", "Despesa")</li>
            <li>@Html.ActionLink("Receitas", "Indice", "Receita")</li>
        </ul>

        @RenderBody()

        @*<div class="top-bar">
                <div class="top-bar-left">
                    <ul class="dropdown menu" data-dropdown-menu>
                        <li class="menu-text">Site Title</li>
                        <li>
                            <a href="#">One</a>
                            <ul class="menu vertical">
                                <li><a href="#">One</a></li>
                                <li><a href="#">Two</a></li>
                                <li><a href="#">Three</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Two</a></li>
                        <li><a href="#">Three</a></li>
                    </ul>
                </div>
                <div class="top-bar-right">
                    <ul class="menu">
                        <li><input type="search" placeholder="Search"></li>
                        <li><button type="button" class="button">Search</button></li>
                    </ul>
                </div>
            </div>*@
    </div>

    @Scripts.Render("~/bundles/foundation")
    <script>
        $(document).foundation();
    </script>
    @*Use the Scripts section to define page specific scripts*@
    @RenderSection("scripts", required: false)
    @*@MiniProfiler.Current.RenderIncludes(position: RenderPosition.Right, showTrivial: false, showTimeWithChildren: false, startHidden: false)*@
</body>
</html>

Finance2/Views/Shared/_PesquisaPartial.cshtml
@model Finance.ViewModels.PesquisaViewModel


@using (Html.BeginForm())
{
    @*@Html.ValidationSummary(true)*@

    /*<div class="form-group">
        @Html.Label("Nome", new { @class = "control-label col-md-1" })
        <div class="col-md-2">
            @Html.TextBox("nome")
        </div>
        <div>
            @*<input type="submit" value="pesquisar" class="btn btn-primary" />*@
            @Html.Button("Buscar", new { @class = "class=btn btn-primary" })
        </div>
    </div>*/

    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-2">
            @Html.TextBoxFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-2">
            @Html.TextBoxFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div>
            @*<input type = "submit" value="pesquisar" class="btn btn-primary" />*@
            @*@Html.Button("Buscar", new { @class = "class=btn btn-primary" })*@
        </div>
    </div>
}